### ISSUE TITLE
TPQ research code isn't working

### ISSUE THREAD

**Issue by jacobnzw** [jacobnzw/SSMToybox#32]
Running `tpq_constant_velocity.py` produces no results. 

Running `tpq_ungm.py` throws up the following error:
```
Traceback (most recent call last):
  File "C:\Users\Jacob\repos\SSMToybox\research\tpq\tpq_ungm.py", line 253, in <module>
    ungm_demo()
  File "C:\Users\Jacob\repos\SSMToybox\research\tpq\tpq_ungm.py", line 55, in ungm_demo
    x = dyn.simulate_discrete(steps, mc_sims)
  File "C:\Users\Jacob\repos\SSMToybox\ssmtoybox\ssmod.py", line 193, in simulate_discrete
    q = self.noise_rv.sample((steps, mc_sims))
  File "C:\Users\Jacob\repos\SSMToybox\research\tpq\tpq_base.py", line 28, in sample
    return np.moveaxis(gauss_mixture(self.means, self.covs, self.alphas, size), -1, 0)
  File "<__array_function__ internals>", line 5, in moveaxis
  File "C:\Users\Jacob\Anaconda3\envs\SSMToybox\lib\site-packages\numpy\core\numeric.py", line 1458, in moveaxis
    a = asarray(a)
  File "C:\Users\Jacob\Anaconda3\envs\SSMToybox\lib\site-packages\numpy\core\_asarray.py", line 102, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (25000,1) into shape (25000,)
```

**Comment by jacobnzw** [comment]
Fixed in the latest commits.
